[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#fcfcfb"
secondaryBackgroundColor = "#f1f0ec"
textColor = "#0b0b0b"
font = "Comfortaa:https://fonts.googleapis.com/css2?family=Comfortaa:wght@300..700&display=swap, sans-serif"
codeFont = "monospace"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
